name: Fancy Solution
title: Fancy Solution - Baked with Awestruct
organization: ExampleCom
base_url: ''
org: MyOrg
com: MyCom

asciidoctor:
  :safe: safe
  :attributes:
    sitename: Fancy Solution
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font